// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euwknsxtanjcbzhjswrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1d2tuc3h0YW5qY2J6aGpzd3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODIxNjEsImV4cCI6MjA2Nzc1ODE2MX0.z3Yzy072wNs2owZnSjbgAiqUQtHtMrkS0vCglmhA6yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});